### ISSUE TITLE
Dibujos Blockly

### ISSUE THREAD

**Issue by alanezz** [OCI-PUC/2017#2]
Los invito a comentar esta issue con el link de sus dibujos en Blockly 😄

**Comment by oancasdis** [comment]
https://blockly-games.appspot.com/turtle-reddit?wq2ocf

**Comment by DarioQloWenon** [comment]
https://blockly-games.appspot.com/turtle?level=10#t3jd85
Mi capacidad mental no da para mas :'(

**Comment by noke-senpai** [comment]
https://blockly-games.appspot.com/turtle?lang=es&level=10#qp894g

bien penca me quedo :v
PD: soy otaku

**Comment by Esteban2003** [comment]
https://blockly-games.appspot.com/turtle?lang=es&level=10
bueno si se es muy fome, pero eso es mi trabajo

**Comment by tuturuuu** [comment]
https://blockly-games.appspot.com/turtle?lang=en&level=10#ingwao (~・ᴗ・)~

**Comment by SebastianQuiros** [comment]
https://blockly-games.appspot.com/turtle?lang=es&level=10#jfqqwy

**Comment by DarioQloWenon** [comment]
https://blockly-games.appspot.com/turtle?lang=es&level=10#ybb99z

ya habia mandado uno, pero prefiero este J E J E

**Comment by ferjosecas** [comment]
https://blockly-games.appspot.com/turtle?lang=es&level=10

**Comment by ferjosecas** [comment]
https://blockly-games.appspot.com/turtle?level=10#8tuh24

**Comment by NicolasCortes100** [comment]
https://blockly-games.appspot.com/turtle?lang=es&level=10#tmp4to
Gotta Catchem All

**Comment by matiasd828** [comment]
https://blockly-games.appspot.com/turtle?level=10#37fomi

**Comment by N1C0l45j** [comment]
https://blockly-games.appspot.com/turtle?level=10#7vj7wg

**Comment by GnesisVSS** [comment]
https://blockly-games.appspot.com/turtle-reddit?7ep723

**Comment by Luissssz** [comment]
https://blockly-games.appspot.com/turtle?level=10#38otco
Imaginación over 9000

**Comment by IAMYISUS** [comment]
https://blockly-games.appspot.com/turtle?level=10#e6gktq
un poco tarde pero aquí esta jsjs

**Comment by cruz** [comment]
Hubo uno que hizo una trifuerza ... pero desapareció :(

**Comment by javisaa** [comment]
https://blockly-games.appspot.com/turtle?lang=es&level=10
:)
