### ISSUE TITLE
¿ El grupo de whatsapp ?

### ISSUE THREAD

**Issue by hernanitop007** [OCI-PUC/2017#4]
Hola, mi pregunta es si el grupo de whatsapp ya esta creado , y si aun no esta creado compartan el enlace por  esta issues por favor para que sea mas fácil  buscarlo 
Eso saludos =)

**Comment by DarioQloWenon** [comment]
Van a hacer un grupo de wsp?, si es asi les pediria si me pueden agregar, hoy no pude ir por temas de saud :( +56945373610

**Comment by alanezz** [comment]
Hola! en la issue #5 contesté esto.

Saludos.
